<div class="product-info-main">
    <div class="page-title-wrapper product">
        <h1 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper" itemprop="name">
                <?php $post = $block->getPortfolio(); echo $post->getTitle(); ?>
            </span>    
        </h1>
    </div>
    <div class="product-info-price">
        <div class="price-box price-final_price" data-role="priceBox" data-product-id="1802" data-price-box="product-id-1802">
            <span class="normal-price">
                <span class="price-container price-final_price tax weee" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
                    <span class="price-label">
                        <?php if (isset($post['description'])) echo $post->getDescription(); ?>
                    </span>
                    <div id="product-price-1802" data-price-amount="34" data-price-type="finalPrice" class="price-wrapper ">
                        <?php if (isset($post['created_at'])) echo $post->getCreatedAt(); ?>
                    </div>
                    <meta itemprop="price" content="34">
                    <meta itemprop="priceCurrency" content="USD">
                </span>
            </span>
        </div>
    </div>
</div>

<div class="product media">
    <?php 
        if (isset($post['image'])) 
        echo "<img class='fotorama__img' src='".$post->getImageUrl()."' alt=''>";
    ?>
</div>